const content = {
fr: {
navProjects:'Projets',navJourney:'Parcours',navSkills:'Compétences',navContact:'Contact',top:'Retour en haut ↑',
role:'Étudiant ingénieur · IA & Data Science',headline:'Des données.<br>Des idées.<br><em>Des solutions.</em>',intro:'Je suis Aymane Chadni, étudiant à l’EMSI Tanger. Je conçois des applications qui relient intelligence artificielle, ingénierie des données et développement web.',view:'Découvrir mes projets',cv:'Télécharger mon CV',location:'Tanger, Maroc · EMSI',portraitRole:'IA & Data Science',student:'Étudiant ingénieur',specialties:['Intelligence artificielle','Ingénierie des données','Développement web'],
projectEyebrow:'01 / Projets sélectionnés',projectTitle:'De la théorie à la pratique.',projectIntro:'Des projets en entreprise et académiques, de l’IA appliquée à la supervision réseau.',details:'Explorer le projet',
projects:[{"date": "2026", "category": "PROJET DE STAGE · BBRS CONSULTING", "title": "DNOC IA Platform", "description": "Une plateforme intelligente de supervision et de diagnostic des infrastructures réseau Aruba, de la collecte des données techniques à la génération de rapports.", "flow": ["Collecte", "Diagnostic", "Rapport"], "label": "AI / NETWORK", "tags": ["Python", "FastAPI", "React", "PostgreSQL", "MinIO", "Ollama", "Docker"], "points": ["Acquisition de données à partir de fichiers CLI et prise en charge d’un mode Live via SSH.", "Reconstruction de la topologie réseau à partir des informations LLDP et suivi des équipements.", "Assistant IA pour interroger les données techniques et accompagner le diagnostic.", "Suivi des alertes, de la fraîcheur des données et des exécutions grâce aux identifiants de run.", "Génération de rapports PDF et Word avec graphiques et plans d’action."]},{date:'MARS — JUIN 2026',category:'PROJET DE FIN D’ANNÉE',title:'E-commerce intelligent',description:'Une plateforme qui associe recommandation, détection de fraude et analyse décisionnelle dans une architecture distribuée.',flow:['Données','Pipeline ETL','Décision'],label:'DATA / COMMERCE',tags:['Python','PySpark','TensorFlow','Power BI','Docker'],points:['Pipeline Big Data de bout en bout avec Data Lake et Data Warehouse.','Système de recommandation et détection de fraude par Deep Learning.','Dashboard BI pour l’analyse des données.','Architecture multi-agents pour automatiser la prise de décision.']},{date:'MARS — MAI 2025',category:'PROJET DE FIN D’ANNÉE',title:'Télémédecine & intelligence artificielle',description:'Une plateforme académique réunissant classification d’images cutanées, prise de rendez-vous et chatbot médical.',flow:['Images','Modèle CNN','API Flask'],label:'AI / HEALTH',tags:['TensorFlow','Flask','Laravel','MySQL','Tailwind CSS'],points:['Conception et entraînement d’un CNN pour la classification d’images médicales.','Mise à disposition du modèle via une API REST Flask.','Interface web de prise de rendez-vous.','Intégration d’un chatbot médical intelligent.']}],
journeyEyebrow:'02 / Expérience & formation',journeyTitle:'Un parcours en construction.',journeyIntro:'Une formation d’ingénieur et une première expérience du développement en entreprise.',journey:[{date:'JUILLET — SEPTEMBRE 2025',type:'Stage d’application',title:'Smart Automation Technologies',subtitle:'Développement web · Tanger',description:'Développement d’une application de gestion de données footballistiques. Modélisation UML et travail en équipe selon la méthodologie Agile Scrum.',tags:['Angular','TypeScript','API REST','HTML / CSS']},{date:'2022 — EN COURS',type:'Formation d’ingénieur',title:'École Marocaine des Sciences de l’Ingénieur',subtitle:'EMSI · Tanger',description:'Ingénierie Informatique & Réseaux, spécialisation Intelligence Artificielle et Data Science.'},{date:'2021 — 2022',type:'Baccalauréat',title:'Baccalauréat international en sciences physiques',subtitle:'Yanboe Annour 2',description:'Option français.'}],
skillsEyebrow:'03 / Compétences',skillsTitle:'Une approche transversale.',skillsIntro:'Des modèles d’IA aux interfaces, en passant par les données.',skills:[['IA & Machine Learning','Machine Learning · Deep Learning · CNN · TensorFlow · Keras · Systèmes multi-agents · IA distribuée'],['Big Data & Business Intelligence','Hadoop · Spark · PySpark · ETL · Pandas · Data Lake · Data Warehouse · Power BI'],['Développement web','Angular · Node.js · Express.js · Laravel · Django · Flask · Bootstrap · Tailwind CSS · HTML · CSS'],['Langages','Python · Java · C · C++ · PHP · JavaScript · TypeScript'],['Bases de données','MySQL · Oracle · SQL Server · MongoDB · Neo4j · Cassandra · Redis'],['Conception & outils','UML · Merise · PowerAMC · MVC · Docker · Scrum · Eclipse · PyCharm · Visual Studio Code']],certTitle:'Formation complémentaire',certProgress:'Oracle · En cours de préparation',duke:'Duke University · Formation mentionnée au CV',languagesTitle:'Langues & savoir-être',languages:'Français : intermédiaire · Anglais : intermédiaire',qualities:'Communication · Esprit d’équipe · Rigueur',
contactEyebrow:'04 / Contact',contactTitle:'Une idée ?<br><em>Échangeons.</em>',contactIntro:'Pour une opportunité de stage ou un échange autour de l’IA, de la data et du développement web.',write:'M’écrire',linkedin:'Mon profil LinkedIn ↗',otherCv:'CV en anglais ↓',skip:'Aller au contenu'
},
en: {
navProjects:'Projects',navJourney:'Experience',navSkills:'Skills',navContact:'Contact',top:'Back to top ↑',role:'Engineering student · AI & Data Science',headline:'Data.<br>Ideas.<br><em>Solutions.</em>',intro:'I’m Aymane Chadni, an engineering student at EMSI Tangier. I build applications that connect artificial intelligence, data engineering and web development.',view:'Explore my projects',cv:'Download my CV',location:'Tangier, Morocco · EMSI',portraitRole:'AI & Data Science',student:'Engineering student',specialties:['Artificial intelligence','Data engineering','Web development'],
projectEyebrow:'01 / Selected projects',projectTitle:'From theory to practice.',projectIntro:'Internship and academic projects, from applied AI to network monitoring.',details:'Explore the project',projects:[{"date": "2026", "category": "INTERNSHIP PROJECT · BBRS CONSULTING", "title": "DNOC IA Platform", "description": "An intelligent platform for monitoring and diagnosing Aruba network infrastructure, from collecting technical data to generating reports.", "flow": ["Collection", "Diagnosis", "Report"], "label": "AI / NETWORK", "tags": ["Python", "FastAPI", "React", "PostgreSQL", "MinIO", "Ollama", "Docker"], "points": ["Data acquisition from CLI files, with support for a Live mode through SSH.", "Network topology reconstruction using LLDP information and device monitoring.", "AI assistant for querying technical data and supporting diagnosis.", "Tracking alerts, data freshness and executions through run identifiers.", "PDF and Word report generation with charts and action plans."]},{date:'MARCH — JUNE 2026',category:'END-OF-YEAR PROJECT',title:'Intelligent e-commerce',description:'A platform combining recommendations, fraud detection and business intelligence within a distributed architecture.',flow:['Data','ETL pipeline','Decision'],label:'DATA / COMMERCE',tags:['Python','PySpark','TensorFlow','Power BI','Docker'],points:['End-to-end Big Data pipeline with a Data Lake and Data Warehouse.','Recommendation system and Deep Learning fraud detection.','BI dashboard for data analysis.','Multi-agent architecture to automate decision-making.']},{date:'MARCH — MAY 2025',category:'END-OF-YEAR PROJECT',title:'Telemedicine & artificial intelligence',description:'An academic platform combining skin image classification, appointment booking and a medical chatbot.',flow:['Images','CNN model','Flask API'],label:'AI / HEALTH',tags:['TensorFlow','Flask','Laravel','MySQL','Tailwind CSS'],points:['Design and training of a CNN for medical image classification.','Model deployment through a Flask REST API.','Web interface for appointment booking.','Integration of an intelligent medical chatbot.']}],
journeyEyebrow:'02 / Experience & education',journeyTitle:'A journey in the making.',journeyIntro:'An engineering education and first-hand experience in professional web development.',journey:[{date:'JULY — SEPTEMBER 2025',type:'Application internship',title:'Smart Automation Technologies',subtitle:'Web development · Tangier',description:'Developed a web application for managing football data. Modeled the system with UML and collaborated using the Agile Scrum methodology.',tags:['Angular','TypeScript','REST API','HTML / CSS']},{date:'2022 — PRESENT',type:'Engineering education',title:'Moroccan School of Engineering Sciences',subtitle:'EMSI · Tangier',description:'Computer Engineering & Networks, specializing in Artificial Intelligence and Data Science.'},{date:'2021 — 2022',type:'Baccalaureate',title:'International Baccalaureate in Physical Sciences',subtitle:'Yanboe Annour 2',description:'French option.'}],
skillsEyebrow:'03 / Skills',skillsTitle:'Connecting disciplines.',skillsIntro:'From AI models to interfaces, with data at the core.',skills:[['AI & Machine Learning','Machine Learning · Deep Learning · CNN · TensorFlow · Keras · Multi-agent systems · Distributed AI'],['Big Data & Business Intelligence','Hadoop · Spark · PySpark · ETL · Pandas · Data Lake · Data Warehouse · Power BI'],['Web development','Angular · Node.js · Express.js · Laravel · Django · Flask · Bootstrap · Tailwind CSS · HTML · CSS'],['Programming languages','Python · Java · C · C++ · PHP · JavaScript · TypeScript'],['Databases','MySQL · Oracle · SQL Server · MongoDB · Neo4j · Cassandra · Redis'],['Design & tools','UML · Merise · PowerAMC · MVC · Docker · Scrum · Eclipse · PyCharm · Visual Studio Code']],certTitle:'Further learning',certProgress:'Oracle · Preparation in progress',duke:'Duke University · Course listed on CV',languagesTitle:'Languages & personal qualities',languages:'French: intermediate · English: intermediate',qualities:'Communication · Teamwork · Attention to detail',
contactEyebrow:'04 / Contact',contactTitle:'Have an idea?<br><em>Let’s talk.</em>',contactIntro:'For an internship opportunity or a conversation about AI, data and web development.',write:'Get in touch',linkedin:'My LinkedIn profile ↗',otherCv:'CV in French ↓',skip:'Skip to content'
}};
const tags = values => `<div class="tags">${values.map(v=>`<span>${v}</span>`).join('')}</div>`;
const heading = (eyebrow,title,intro)=>`<div class="section-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div><p>${intro}</p></div>`;
function render(lang){
 const t=content[lang];document.documentElement.lang=lang;
 document.title=`Aymane Chadni — ${lang==='fr'?'IA':'AI'} & Data Science`;
 document.querySelector('meta[name="description"]').content=lang==='fr'?'Portfolio d’Aymane Chadni, étudiant ingénieur en IA et Data Science à l’EMSI Tanger. Projets, compétences et parcours.':'Aymane Chadni’s portfolio. AI and Data Science engineering student at EMSI Tangier. Projects, skills and experience.';
 document.querySelectorAll('[data-text]').forEach(el=>el.textContent=t[el.dataset.text]);
 document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));
 document.getElementById('skip').textContent=t.skip;
 document.getElementById('main').innerHTML=`
 <section class="hero"><div><p class="eyebrow">${t.role}</p><h1>${t.headline}</h1><p class="intro">${t.intro}</p><div class="actions"><a class="button primary" href="#projects">${t.view}<span aria-hidden="true">↗</span></a><a class="button" href="assets/cv-${lang}.pdf" download="Aymane-Chadni-CV-${lang}.pdf">${t.cv}<span aria-hidden="true">↓</span></a></div><p class="location">${t.location}</p></div><div class="portrait-card"><div class="card-top"><span>PORTFOLIO / AC</span><span>AI & DATA</span></div><img class="portrait" src="assets/portrait.png" width="377" height="377" alt="Aymane Chadni"><div class="card-bottom"><div><strong>Aymane Chadni</strong><small>${t.portraitRole}</small></div><span class="badge">${t.student}</span></div></div></section>
 <div class="specialties">${t.specialties.map(s=>`<span>${s}</span>`).join('')}</div>
 <section class="content" id="projects">${heading(t.projectEyebrow,t.projectTitle,t.projectIntro)}<div class="project-grid">${t.projects.map((p,i)=>`<article class="project"><div class="project-visual"><div class="visual-label"><span>${p.label}</span><span>0${i+1}</span></div><div class="flow">${p.flow.map((f,n)=>`${n?'<i aria-hidden="true">→</i>':''}<span>${f}</span>`).join('')}</div></div><div class="project-body"><span class="meta">${p.date} · ${p.category}</span><h3>${p.title}</h3><p>${p.description}</p>${tags(p.tags)}<details><summary>${t.details}</summary><ul>${p.points.map(pt=>`<li>${pt}</li>`).join('')}</ul></details></div></article>`).join('')}</div></section>
 <section class="content journey" id="journey">${heading(t.journeyEyebrow,t.journeyTitle,t.journeyIntro)}${t.journey.map(j=>`<article class="timeline"><div><time>${j.date}</time><span class="type">${j.type}</span></div><div><h3>${j.title}</h3><span class="meta">${j.subtitle}</span><p>${j.description}</p>${j.tags?tags(j.tags):''}</div></article>`).join('')}</section>
 <section class="content" id="skills">${heading(t.skillsEyebrow,t.skillsTitle,t.skillsIntro)}<div class="skill-grid">${t.skills.map((s,i)=>`<div class="skill"><span class="number">0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></div>`).join('')}</div><div class="extras"><div><h3>${t.certTitle}</h3><div class="cert"><strong>Oracle Database 19c Admin Professional Credential</strong><p>${t.certProgress}</p></div><div class="cert"><strong>Introduction to Machine Learning</strong><p>${t.duke}</p></div></div><div><h3>${t.languagesTitle}</h3><p>${t.languages}</p><p>${t.qualities}</p></div></div></section>
 <section class="contact" id="contact"><div><p class="eyebrow">${t.contactEyebrow}</p><h2>${t.contactTitle}</h2><p>${t.contactIntro}</p></div><div class="contact-links"><a class="email" href="mailto:Aymane.Chadni@emsi-edu.ma">Aymane.Chadni@emsi-edu.ma</a><a class="button" href="mailto:Aymane.Chadni@emsi-edu.ma">${t.write}<span aria-hidden="true">↗</span></a><a class="social" href="https://www.linkedin.com/in/aymane-chadni-926053337/" target="_blank" rel="noopener noreferrer">${t.linkedin}</a><a class="social" href="assets/cv-${lang==='fr'?'en':'fr'}.pdf" download>${t.otherCv}</a></div></section>`;
}
let lang='fr';try{if(localStorage.getItem('portfolio-language')==='en')lang='en';}catch{}
render(lang);
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{render(button.dataset.lang);try{localStorage.setItem('portfolio-language',button.dataset.lang);}catch{}}));
document.getElementById('year').textContent=new Date().getFullYear();
